const fs = require('fs');
const path = require('path');

const stocks = [
    {name: 'Adani Ports and SEZ', nse: 'ADANIPORTS', bse: '541387'},
    {name: 'Asian Paints', nse: 'ASIANPAINT', bse: '500820'},
    {name: 'Axis Bank', nse: 'AXISBANK', bse: '532215'},
    {name: 'Bajaj Auto', nse: 'BAJAJ-AUTO', bse: '532977'},
    {name: 'Bharat Petroleum', nse: 'BPCL', bse: '500547'},
    {name: 'Bharti Airtel', nse: 'BHARTIARTL', bse: '532454'},
    {name: 'Britannia Industries', nse: 'BRITANNIA', bse: '500825'},
    {name: 'Cipla', nse: 'CIPLA', bse: '500087'},
    {name: 'Coal India', nse: 'COALINDIA', bse: '533278'},
    {name: "Dr. Reddy's Laboratories", nse: 'DRREDDY', bse: '500124'},
    {name: 'Eicher Motors', nse: 'EICHERMOT', bse: '505200'},
    {name: 'Grasim Industries', nse: 'GRASIM', bse: '500300'},
    {name: 'HCL Technologies', nse: 'HCLTECH', bse: '532281'},
    {name: 'HDFC Bank', nse: 'HDFCBANK', bse: '500180'},
    {name: 'Hero MotoCorp', nse: 'HEROMOTOCO', bse: '500182'},
    {name: 'Hindalco Industries', nse: 'HINDALCO', bse: '500440'},
    {name: 'Hindustan Unilever', nse: 'HINDUNILVR', bse: '500696'},
    {name: 'ICICI Bank', nse: 'ICICIBANK', bse: '532174'},
    {name: 'Indian Oil Corporation', nse: 'IOC', bse: '530965'},
    {name: 'Infosys', nse: 'INFY', bse: '500209'},
    {name: 'ITC Limited', nse: 'ITC', bse: '500875'},
    {name: 'JSW Steel', nse: 'JSWSTEEL', bse: '500228'},
    {name: 'Larsen & Toubro', nse: 'LT', bse: '500040'},
    {name: 'Mahindra & Mahindra', nse: 'M&M', bse: '500520'},
    {name: 'Maruti Suzuki', nse: 'MARUTI', bse: '532500'},
    {name: 'Nestlé India', nse: 'NESTLEIND', bse: '500790'},
    {name: 'NTPC', nse: 'NTPC', bse: '532555'},
    {name: 'Oil and Natural Gas Corporation', nse: 'ONGC', bse: '500312'},
    {name: 'Power Grid Corporation', nse: 'POWERGRID', bse: '532898'},
    {name: 'Reliance Industries', nse: 'RELIANCE', bse: '500325'},
    {name: 'SBI', nse: 'SBIN', bse: '500112'},
    {name: 'Sun Pharmaceutical Industries', nse: 'SUNPHARMA', bse: '524715'},
    {name: 'Tata Consultancy Services', nse: 'TCS', bse: '532540'},
    {name: 'Tata Motors', nse: 'TATAMOTORS', bse: '500570'},
    {name: 'Tata Steel', nse: 'TATASTEEL', bse: '500470'},
    {name: 'Tech Mahindra', nse: 'TECHM', bse: '532755'},
    {name: 'UltraTech Cement', nse: 'ULTRACEMCO', bse: '532538'},
    {name: 'Wipro', nse: 'WIPRO', bse: '507685'},
    {name: 'Zee Entertainment Enterprises', nse: 'ZEEL', bse: '505537'},
    {name: 'Hindustan Aeronautics', nse: 'HAL', bse: '541154'},
    {name: 'Minda Industries', nse: 'MINDAIND', bse: '532539'},
    {name: 'L&T Technology Services', nse: 'LTTS', bse: '540115'},
    {name: 'MRF', nse: 'MRF', bse: '500290'},
    {name: 'Bajaj Holdings', nse: 'BAJHOLDING', bse: '500490'},
    {name: "Divi's Laboratories", nse: 'DIVISLAB', bse: '532488'},
    {name: 'HDFC Life Insurance', nse: 'HDFCLIFE', bse: '540777'},
    {name: 'ABB India', nse: 'ABB', bse: '500002'},
    {name: 'Adani Ports and SEZ', nse: 'ADANIPORTS', bse: '541387'},
    {name: 'Adani Green Energy', nse: 'ADANIGREEN', bse: '541450'},
    {name: 'Asian Paints', nse: 'ASIANPAINT', bse: '500820'},
    {name: 'Axis Bank', nse: 'AXISBANK', bse: '532215'},
    {name: 'ABB India', nse: 'ABB', bse: '500002'},
    {name: 'Aurobindo Pharma', nse: 'AUROPHARMA', bse: '524804'},
    {name: 'Adani Wilmar', nse: 'ADANIWILMAR', bse: '543512'},
    ,
    {name: 'Ambuja Cements', nse: 'AMBUJACEM', bse: '500425'},
    {name: 'Adani Ports and SEZ', nse: 'ADANIPORTS', bse: '541387'},
    {name: 'Adani Wilmar', nse: 'ADANIWILMAR', bse: '543512'},
    {name: 'Asian Paints', nse: 'ASIANPAINT', bse: '500820'},
    {name: 'Axis Bank', nse: 'AXISBANK', bse: '532215'},
    {name: 'ABB India', nse: 'ABB', bse: '500002'},
    {name: 'Aurobindo Pharma', nse: 'AUROPHARMA', bse: '524804'},
    {name: 'Ambuja Cements', nse: 'AMBUJACEM', bse: '500425'},
    {name: 'Ashok Leyland', nse: 'ASHOKLEY', bse: '500477'},
    {name: 'Apollo Hospitals', nse: 'APOLLOHOSP', bse: '508869'},
    {name: 'Aegis Logistics', nse: 'AEGISCHEM', bse: '500008'},
    {name: 'Asian Energy Services', nse: 'ASIANENE', bse: '540685'},
    {name: 'Adani Ports and SEZ', nse: 'ADANIPORTS', bse: '541387'},
    {name: 'Adani Green Energy', nse: 'ADANIGREEN', bse: '541450'},
    {name: 'Adani Wilmar', nse: 'ADANIWILMAR', bse: '543512'},
    {name: 'Asian Paints', nse: 'ASIANPAINT', bse: '500820'},
    {name: 'Axis Bank', nse: 'AXISBANK', bse: '532215'},
    {name: 'ABB India', nse: 'ABB', bse: '500002'},
    {name: 'Aurobindo Pharma', nse: 'AUROPHARMA', bse: '524804'},
    {name: 'Alkem Laboratories', nse: 'ALKEM', bse: '539523'},
    {name: 'Ambuja Cements', nse: 'AMBUJACEM', bse: '500425'},
    {name: 'Ashok Leyland', nse: 'ASHOKLEY', bse: '500477'},
    {name: 'Apollo Hospitals', nse: 'APOLLOHOSP', bse: '508869'},
    {name: 'Aegis Logistics', nse: 'AEGISCHEM', bse: '500008'},
    {name: 'Asian Energy Services', nse: 'ASIANENE', bse: '540685'},
    {name: 'AstraZeneca Pharma', nse: 'ASTRAZEN', bse: '506481'},
    {name: 'Avanti Feeds', nse: 'AVANTIFEED', bse: '512573'},
    {name: 'Alembic Pharmaceuticals', nse: 'APLLTD', bse: '533573'},
    {name: 'Allied Blenders and Distillers', nse: 'ABD', bse: '534634'},
    {name: 'Bajaj Auto', nse: 'BAJAJ-AUTO', bse: '532977'},
    {name: 'Bajaj Finance', nse: 'BAJFINANCE', bse: '500034'},
    {name: 'Bharat Petroleum', nse: 'BPCL', bse: '500547'},
    {name: 'Bharti Airtel', nse: 'BHARTIARTL', bse: '532454'},
    {name: 'Britannia Industries', nse: 'BRITANNIA', bse: '500825'},
    {name: 'Cipla', nse: 'CIPLA', bse: '500087'},
    {name: 'Bharat Electronics', nse: 'BEL', bse: '500049'},
    {name: 'Bharat Forge', nse: 'BHARATFORG', bse: '500493'},
    {name: 'Biocon', nse: 'BIOCON', bse: '532523'},
    {name: 'Bharti Infratel', nse: 'BHARATIN', bse: '540006'},
    {name: 'BSE', nse: 'BSE', bse: '540073'},
    {name: 'Balkrishna Industries', nse: 'BALKRISIND', bse: '502355'},
    {name: 'Bharat Wire Ropes', nse: 'BWR', bse: '540171'},
    {name: 'Bandhan Bank', nse: 'BANDHANBNK', bse: '541153'},
    {name: 'Bank of Baroda', nse: 'BANKBARODA', bse: '501801'},
    {name: 'Bharat Heavy Electricals', nse: 'BHEL', bse: '500103'},
    {name: 'Bombay Dyeing', nse: 'BOMDYEING', bse: '500057'},
    {name: 'Birla Corporation', nse: 'BIRLACORPN', bse: '500335'},
    {name: 'Blue Star', nse: 'BLUESTARCO', bse: '500028'},
    {name: 'Bajaj Auto', nse: 'BAJAJ-AUTO', bse: '532977'},
    {name: 'Bharat Petroleum', nse: 'BPCL', bse: '500547'},
    {name: 'Bharti Airtel', nse: 'BHARTIARTL', bse: '532454'},
    {name: 'Britannia Industries', nse: 'BRITANNIA', bse: '500825'},
    {name: 'Bharat Electronics', nse: 'BEL', bse: '500049'},
    {name: 'Bharat Forge', nse: 'BHARATFORG', bse: '500493'},
    {name: 'Biocon', nse: 'BIOCON', bse: '532523'},
    {name: 'Bharti Infratel', nse: 'BHARATIN', bse: '540006'},
    {name: 'BSE', nse: 'BSE', bse: '540073'},
    {name: 'Balkrishna Industries', nse: 'BALKRISIND', bse: '502355'},
    {name: 'Bombay Dyeing', nse: 'BOMDYEING', bse: '500057'},
    {name: 'Birla Corporation', nse: 'BIRLACORPN', bse: '500335'},
    {name: 'Bandhan Bank', nse: 'BANDHANBNK', bse: '541153'},
    {name: 'Bank of Baroda', nse: 'BANKBARODA', bse: '501801'},
    {name: 'Bharat Heavy Electricals', nse: 'BHEL', bse: '500103'},
    {name: 'Blue Star', nse: 'BLUESTARCO', bse: '500028'},
    {name: 'Bharat Road Network', nse: 'BRNL', bse: '540634'},
    {name: 'Bengaluru International Airport', nse: 'BIAL', bse: '540965'},
    {name: 'Bombay Stock Exchange', nse: 'BSE', bse: '540073'},
    {name: 'Bharat Forge', nse: 'BHARATFORG', bse: '500493'},
    {name: 'Bristol Myers Squibb', nse: 'BMS', bse: '539892'},
    {name: 'Brihans Natural Products', nse: 'BRIHANS', bse: '539878'},
    {name: 'BSE Ltd.', nse: 'BSE', bse: '540073'},
    {name: 'Bharat Immunologicals & Biologicals Corporation', nse: 'BIBCOL', bse: '531262'},
    {name: 'Balaji Telefilms', nse: 'BALAJITELE', bse: '532504'},
    {name: 'Bajaj Holdings', nse: 'BAJHOLDING', bse: '500490'},
    {name: 'Bharat Dynamics', nse: 'BDL', bse: '541143'},
    {name: 'Bharat Wire Ropes', nse: 'BWR', bse: '540171'},
    {name: 'Bharat Forge', nse: 'BHARATFORG', bse: '500493'},
    {name: 'Bharat Rasayan', nse: 'BRL', bse: '524224'},
    {name: 'Bharat Agri Fert & Realty', nse: 'BAGFIL', bse: '526699'},
    {name: 'Bharat Financial Inclusion', nse: 'BFIL', bse: '540613'},
    {name: 'Bharat Heavy Electricals Ltd.', nse: 'BHEL', bse: '500103'},
    {name: 'Bharat Petroleum Corporation', nse: 'BPCL', bse: '500547'},
    {name: 'Bharat Electronics Ltd.', nse: 'BEL', bse: '500049'},
    {name: 'Bharat Forge Ltd.', nse: 'BHARATFORG', bse: '500493'},
    {name: 'Bajaj Finserv Ltd.', nse: 'BAJAJFINSV', bse: '532978'},
    {name: 'Balkrishna Industries Ltd.', nse: 'BALKRISIND', bse: '502355'},
    {name: 'Bata India Ltd.', nse: 'BATAINDIA', bse: '500043'},
    {name: 'Cipla', nse: 'CIPLA', bse: '500087'},
    {name: 'Coal India', nse: 'COALINDIA', bse: '533278'},
    {name: 'Crompton Greaves Consumer Electricals', nse: 'CROMPTON', bse: '541742'},
    {name: 'Cholamandalam Investment and Finance Company', nse: 'CHOLAFIN', bse: '540677'},
    {name: 'CESC Limited', nse: 'CESC', bse: '500084'},
    {name: 'Cairn India', nse: 'CIL', bse: '532792'},
    {name: 'Canara Bank', nse: 'CANBK', bse: '532483'},
    {name: 'Container Corporation of India', nse: 'CONCOR', bse: '532348'},
    {name: 'Cochin Shipyard', nse: 'COCHINSHIP', bse: '540678'},
    {name: 'Crompton Greaves', nse: 'CROMPTON', bse: '500093'},
    {name: 'Cummins India', nse: 'CUMMINSIND', bse: '500480'},
    {name: 'Capgemini Technology Services India', nse: 'CAPGEMINI', bse: '539477'},
    {name: 'City Union Bank', nse: 'CUB', bse: '533397'},
    {name: 'Cedar Communications', nse: 'CEDAR', bse: '534090'},
    {name: 'CreditAccess Grameen', nse: 'CREDACC', bse: '541525'},
    {name: 'Crompton', nse: 'CROMPTON', bse: '541742'},
    {name: 'Chennai Petroleum Corporation', nse: 'CHENNPETRO', bse: '500100'},
    {name: 'Colgate-Palmolive (India)', nse: 'COLPAL', bse: '500830'},
    {name: 'Chetak Logistics', nse: 'CHETAK', bse: '543695'},
    {name: 'Cox and Kings', nse: 'COXANDKINGS', bse: '533146'},
    {name: 'C & C Constructions', nse: 'CCCL', bse: '532404'},
    {name: 'Cleveland Cliffs', nse: 'CLF', bse: '543220'},
    {name: 'Crompton Greaves Consumer', nse: 'CROMPTON', bse: '541742'},
    {name: 'Cipla Health', nse: 'CIPLHEALTH', bse: '542812'},
    {name: 'Cholamandalam Financial Holdings', nse: 'CHOLAFIN', bse: '540677'},
    {name: 'Container Corporation', nse: 'CONCOR', bse: '532348'},
    {name: 'Cairn Energy', nse: 'CNE', bse: '526901'},
    {name: 'Cargill India', nse: 'CARGILL', bse: '530050'},
    {name: 'Crompton Greaves Consumer', nse: 'CROMPTON', bse: '541742'},
    {name: 'Cargill India', nse: 'CARGILL', bse: '530050'},
    {name: 'Central Bank of India', nse: 'CENTRALBK', bse: '532210'},
    {name: 'Cochin Shipyard Ltd.', nse: 'COCHINSHIP', bse: '540678'},
    {name: 'Cera Sanitaryware', nse: 'CERA', bse: '532978'},
    {name: 'Crompton Greaves', nse: 'CROMPTON', bse: '500093'},
    {name: 'Centurion Bank of Punjab', nse: 'CENBANK', bse: '532905'},
    {name: 'CESC Ltd.', nse: 'CESC', bse: '500084'},
    {name: 'Cochin Shipyard Ltd.', nse: 'COCHINSHIP', bse: '540678'},
    {name: 'Consolidated Construction Consortium', nse: 'CCCL', bse: '532404'},
    {name: 'Chemplast Sanmar', nse: 'CHEMPLAST', bse: '500160'},

    {name: "Divi's Laboratories", nse: 'DIVISLAB', bse: '532488'},
    {name: 'Dabur India', nse: 'DABUR', bse: '500096'},
    {name: "Dr. Reddy's Laboratories", nse: 'DRREDDY', bse: '500124'},
    {name: 'HDFC Bank', nse: 'HDFCBANK', bse: '500180'}, // Adding for reference
    {name: 'Dhanlaxmi Bank', nse: 'DHANBANK', bse: '532135'},
    {name: 'Delta Corp', nse: 'DELTACORP', bse: '511147'},
    {name: 'Dewan Housing Finance Corporation', nse: 'DHFL', bse: '511072'},
    {name: 'Deepak Nitrite', nse: 'DEEPAKNTR', bse: '506401'},
    {name: 'Dixon Technologies', nse: 'DIXON', bse: '540699'},
    {name: 'Dr. Lal PathLabs', nse: 'LALPATHLAB', bse: '539524'},
    {name: 'Dabur International', nse: 'DABINTL', bse: '540102'},
    {name: 'Dhanuka Agritech', nse: 'DHANUKA', bse: '507717'},
    {name: 'Dhampur Sugar', nse: 'DHAMPURSUG', bse: '500109'},
    {name: 'Deepak Cables', nse: 'DEEPAKCABLES', bse: '539260'},
    {name: 'Dhanlaxmi Bank', nse: 'DHANBANK', bse: '532135'},
    {name: 'Dewan Housing', nse: 'DHFL', bse: '511072'},
    {name: 'DPSG Global', nse: 'DPSG', bse: '540034'},
    {name: 'Dhanraj Constructions', nse: 'DHANRAJ', bse: '531106'},
    {name: 'Dolly Khanna Investments', nse: 'DOLLYK', bse: '540095'},
    {name: 'Dartmouth Digital', nse: 'DARTMOUTH', bse: '543989'},
    {name: 'DHL Express India', nse: 'DHL', bse: '500145'},
    {name: 'Duke Offshore', nse: 'DUKE', bse: '540129'},
    {name: 'Dharampal Satyapal', nse: 'DHARMSAT', bse: '530903'},
    {name: 'Dabur Foods', nse: 'DABFOOD', bse: '540153'},
    {name: 'Datamatics Global Services', nse: 'DATAMATICS', bse: '532528'},
    {name: 'Dhanraj Satyapal', nse: 'DHANRAJ', bse: '540154'},
    {name: 'Davis Infrastructure', nse: 'DAVIS', bse: '543221'},
    {name: 'Dhanuka Agritech', nse: 'DHANUKA', bse: '507717'},
    {name: 'Dunlop India', nse: 'DUNLOP', bse: '507108'},
    {name: 'Dharamsi Morarji Chemical', nse: 'DMCC', bse: '501193'},
    {name: 'Dharampal Satyapal', nse: 'DHARMSAT', bse: '530903'},
    {name: 'Deltin Hotels', nse: 'DELTIN', bse: '543722'},
    {name: 'Dabur Foods', nse: 'DABFOOD', bse: '540153'},
    {name: 'Dhanraj Cables', nse: 'DHANRAJCABLES', bse: '540167'},
    {name: 'Deccan Cements', nse: 'DECCANCEM', bse: '502137'},
    {name: 'DB Corp', nse: 'DBCORP', bse: '533151'},
    {name: 'Dalmia Bharat', nse: 'DALMIABHA', bse: '543243'},
    {name: 'Deepak Fertilisers', nse: 'DEEPAKFERT', bse: '500645'},
    {name: 'Dawn Mills', nse: 'DAWN', bse: '543302'},
    {name: 'Dharampal Satyapal', nse: 'DHARMSAT', bse: '530903'},
    {name: 'Dena Bank', nse: 'DENABANK', bse: '511006'},
    {name: 'Dhanlaxmi Bank', nse: 'DHANBANK', bse: '532135'},
    {name: 'Devang House', nse: 'DEVANG', bse: '540102'},
    {name: 'Dharamsi Morarji Chemical', nse: 'DMCC', bse: '501193'},
    {name: 'Daya Geco', nse: 'DAYAGECO', bse: '543110'},
    {name: 'Dharampal Satyapal', nse: 'DHARMSAT', bse: '530903'},
    {name: 'Dena Bank', nse: 'DENABANK', bse: '511006'},
    {name: 'Dharamsi Morarji Chemical', nse: 'DMCC', bse: '501193'},
    {name: 'Dena Bank', nse: 'DENABANK', bse: '511006'},
    {name: 'Dhanlaxmi Bank', nse: 'DHANBANK', bse: '532135'},
    {name: 'Eicher Motors', nse: 'EICHERMOT', bse: '505200'},
    {name: 'Eldeco Housing & Industries', nse: 'EDELHOUSING', bse: '500179'},
    {name: 'Emami', nse: 'EMAMILTD', bse: '524148'},
    {name: 'Engineers India', nse: 'ENGINERSIN', bse: '532178'},
    {name: 'Eveready Industries India', nse: 'EVERREADY', bse: '500123'},
    {name: 'Eros International Media', nse: 'EROSMEDIA', bse: '534242'},
    {name: 'Electrosteel Steels', nse: 'ELECTROSTEEL', bse: '513523'},
    {name: 'Eagle Eye Equities', nse: 'EAGLE', bse: '534232'},
    {name: 'Essar Oil', nse: 'ESSAROIL', bse: '533141'},
    {name: 'EID Parry India', nse: 'EIDPARRY', bse: '500125'},
    {name: 'Eureka Forbes', nse: 'EUREKA', bse: '500191'},
    {name: 'Eagle Eye Equities', nse: 'EAGLE', bse: '534232'},
    {name: 'Ernst & Young', nse: 'EY', bse: '543456'},
    {name: 'Essar Ports', nse: 'ESSARPORT', bse: '533140'},
    {name: 'Emami Realty', nse: 'EMAMIREALTY', bse: '535036'},
    {name: 'Eros Now', nse: 'EROSNOW', bse: '543722'},
    {name: 'Edelweiss Financial Services', nse: 'EDELWEISS', bse: '534148'},
    {name: 'Elgi Equipments', nse: 'ELGIEQUIP', bse: '522074'},
    {name: 'EMC Ltd.', nse: 'EMC', bse: '533093'},
    {name: 'Empire Industries', nse: 'EMPIREIND', bse: '509117'},
    {name: 'Essar Global', nse: 'ESSARGLOBAL', bse: '534835'},
    {name: 'EPC Industries', nse: 'EPCIND', bse: '539797'},
    {name: 'Evergreen Products', nse: 'EVERGREEN', bse: '534305'},
    {name: 'Eastern Silk Industries', nse: 'EASTSILK', bse: '507206'},
    {name: 'EIL', nse: 'EIL', bse: '531985'},
    {name: 'Eros Media', nse: 'EROSMEDIA', bse: '534242'},
    {name: 'Electrosteel Steels', nse: 'ELECTROSTEEL', bse: '513523'},
    {name: 'Elgi Equipments', nse: 'ELGIEQUIP', bse: '522074'},
    {name: 'Edelweiss Capital', nse: 'EDELWEISS', bse: '534148'},
    {name: 'Eros International', nse: 'EROSINTL', bse: '543211'},
    {name: 'Everest Industries', nse: 'EVERESTIND', bse: '509490'},
    {name: 'Elantas Beck India', nse: 'ELANTAS', bse: '533115'},
    {name: 'Eris Lifesciences', nse: 'ERISLIFE', bse: '540686'},
    {name: 'Eagle Eye Equities', nse: 'EAGLE', bse: '534232'},
    {name: 'Essar Oil', nse: 'ESSAROIL', bse: '533141'},
    {name: 'Elekta India', nse: 'ELEKTA', bse: '543876'},
    {name: 'Equitas Holdings', nse: 'EQUITAS', bse: '539322'},
    {name: 'EIH Limited', nse: 'EIHOTEL', bse: '500840'},
    {name: 'Eros Now Media', nse: 'EROSNOW', bse: '543722'},
    {name: 'EMC Ltd.', nse: 'EMC', bse: '533093'},
    {name: 'Eagle Eye Equities', nse: 'EAGLE', bse: '534232'},
    {name: 'Eveready Industries', nse: 'EVERREADY', bse: '500123'},
    {name: 'Essar Ports', nse: 'ESSARPORT', bse: '533140'},
    {name: 'Emami Realty', nse: 'EMAMIREALTY', bse: '535036'},
    {name: 'Electrotherm India', nse: 'ELECTRO', bse: '533205'},

    {name: 'Federal Bank', nse: 'FEDERALBNK', bse: '500469'},
    {name: 'Fortis Healthcare', nse: 'FORTIS', bse: '532843'},
    {name: 'Firstsource Solutions', nse: 'FSL', bse: '532809'},
    {name: 'Finolex Industries', nse: 'FINOLEXIND', bse: '500144'},
    {name: 'FMCG Corporation', nse: 'FMCG', bse: '543126'},
    {name: 'Foseco India', nse: 'FOSECOIND', bse: '500150'},
    {name: 'Florentia', nse: 'FLOR', bse: '539480'},
    {name: 'Force Motors', nse: 'FORCEMOT', bse: '500034'},
    {name: 'Financial Technologies', nse: 'FTIL', bse: '532621'},
    {name: 'Firstsource Solutions Ltd.', nse: 'FSL', bse: '532809'},
    {name: 'Ferro Alloys Corporation', nse: 'FACOR', bse: '513687'},
    {name: 'Fintech Global', nse: 'FINTECH', bse: '543212'},
    {name: 'Fineotex Chemical', nse: 'FINEOTEX', bse: '540279'},
    {name: 'Fag Bearings India', nse: 'FAGBEARINGS', bse: '522190'},
    {name: 'Foxconn Technology', nse: 'FOXCONN', bse: '541166'},
    {name: 'Fresenius Kabi Oncology', nse: 'FRESENIUS', bse: '539371'},
    {name: 'FICCI', nse: 'FICCI', bse: '540371'},
    {name: 'FSL', nse: 'FSL', bse: '532809'},
    {name: 'Franco-Indian Pharmaceuticals', nse: 'FRANCOIND', bse: '531749'},
    {name: 'Felicity Enterprises', nse: 'FELICITY', bse: '541190'},
    {name: 'Fazilka Infrastructure', nse: 'FAZILKA', bse: '540200'},
    {name: 'Fiftytwo Technologies', nse: 'FIFTYTWOTEC', bse: '540156'},
    {name: 'Flameproofs', nse: 'FLAMEPROOF', bse: '540123'},
    {name: 'Flares & Flares', nse: 'FLARES', bse: '541207'},
    {name: 'Futura', nse: 'FUTURA', bse: '539197'},
    {name: 'Fashion', nse: 'FASHION', bse: '540110'},
    {name: 'Folkley', nse: 'FOLKLEY', bse: '540222'},
    {name: 'Fortune Brands', nse: 'FORTUNE', bse: '532031'},
    {name: 'Freesoul', nse: 'FREESOUL', bse: '540066'},
    {name: 'Flair Tones', nse: 'FLAIRTONES', bse: '540002'},
    {name: 'Ferro Alloys Corporation Ltd.', nse: 'FACOR', bse: '513687'},
    {name: 'Fine Foods', nse: 'FINEFOODS', bse: '540195'},
    {name: 'Flemingo International', nse: 'FLEMINGO', bse: '533122'},
    {name: 'Fidelis Corporate', nse: 'FIDELIS', bse: '540112'},
    {name: 'Fabrinet', nse: 'FABRINET', bse: '541186'},
    {name: 'Frisco', nse: 'FRISCO', bse: '540108'},
    {name: 'Fosroc', nse: 'FOSROC', bse: '543450'},
    {name: 'Ferry Logistics', nse: 'FERRY', bse: '540087'},
    {name: 'Futuro', nse: 'FUTURO', bse: '540202'},
    {name: 'Foxcon', nse: 'FOXCON', bse: '540155'},
    {name: 'Ferozsons Laboratories', nse: 'FEROZSONS', bse: '540209'},
    {name: 'Grasim Industries', nse: 'GRASIM', bse: '500300'},
    {name: 'GAIL (India)', nse: 'GAIL', bse: '532155'},
    {name: 'Godrej Consumer Products', nse: 'GODREJCP', bse: '532424'},
    {name: 'GlaxoSmithKline Pharmaceuticals', nse: 'GLAND', bse: '500670'},
    {name: 'Gujarat Gas', nse: 'GUJGAZ', bse: '539336'},
    {name: 'GMR Infrastructure', nse: 'GMRINFRA', bse: '532754'},
    {name: 'Glenmark Pharmaceuticals', nse: 'GLENMARK', bse: '532296'},
    {name: 'Gujarat Pipavav Port', nse: 'GPPL', bse: '533248'},
    {name: 'Godrej Properties', nse: 'GODREJPROP', bse: '533150'},
    {name: 'Grindwell Norton', nse: 'GRINDWELL', bse: '500179'},
    {name: 'Gujarat Ambuja Exports', nse: 'GAEL', bse: '524226'},
    {name: 'GMM Pfaudler', nse: 'GMM', bse: '500171'},
    {name: 'Gujarat NRE Coke', nse: 'GNRE', bse: '532731'},
    {name: 'Gateway Distriparks', nse: 'GATEWAY', bse: '532621'},
    {name: 'Gujarat Fluorochemicals', nse: 'GUJFLUORO', bse: '500101'},
    {name: 'Genus Prime Infra', nse: 'GENUS', bse: '540059'},
    {name: 'GE Power India', nse: 'GEPOWER', bse: '533291'},
    {name: 'Gujarat State Fertilizers', nse: 'GSFC', bse: '509415'},
    {name: 'GTL Limited', nse: 'GTL', bse: '532774'},
    {name: 'Godrej Agrovet', nse: 'GODREJAGRO', bse: '540743'},
    {name: 'Gujarat Gas Company', nse: 'GUJGAZ', bse: '539336'},
    {name: 'GMR Airports', nse: 'GMRAP', bse: '540345'},
    {name: 'Gujarat Mineral Development Corporation', nse: 'GMDCLTD', bse: '533168'},
    {name: 'Granules India', nse: 'GRANULES', bse: '532485'},
    {name: 'Golkonda Resources', nse: 'GOLKONDA', bse: '530031'},
    {name: 'Graphite India', nse: 'GRAPHITE', bse: '509488'},
    {name: 'Goa Carbon', nse: 'GOACARBON', bse: '509567'},
    {name: 'Goodyear India', nse: 'GOODYEAR', bse: '500168'},
    {name: 'Gujarat Sidhee Cement', nse: 'GUJARATSID', bse: '502171'},
    {name: 'Gujarat Industries Power Company', nse: 'GIPCL', bse: '523409'},
    {name: 'Gujarat Reclaim and Rubber Products', nse: 'GCRRP', bse: '530445'},
    {name: 'Gujarat Pipavav Port Ltd.', nse: 'GPPL', bse: '533248'},
    {name: 'Gujarat Fluorochemicals Ltd.', nse: 'GUJFLUORO', bse: '500101'},
    {name: 'Gokaldas Exports', nse: 'GOKALDAS', bse: '530089'},
    {name: 'Gujarat State Petronet', nse: 'GSPL', bse: '532702'},
    {name: 'Gyan Dairy', nse: 'GYANDAIRY', bse: '540888'},
    {name: 'Greenply Industries', nse: 'GREENPLY', bse: '526787'},
    {name: 'GMR Infrastructure Limited', nse: 'GMRINFRA', bse: '532754'},
    {name: 'Greenlam Industries', nse: 'GREENLAM', bse: '539333'},
    {name: 'Gokul Agro Resources', nse: 'GOKUL', bse: '539036'},
    {name: 'Gujarat Mineral Development', nse: 'GMDCLTD', bse: '533168'},
    {name: 'Goldiam International', nse: 'GOLDIAM', bse: '500245'},
    {name: 'Gokul Agro Resources Ltd.', nse: 'GOKUL', bse: '539036'},
    {name: 'Geetanjali Gems', nse: 'GEETANJALI', bse: '533185'},
    {name: 'HDFC Bank', nse: 'HDFCBANK', bse: '500180'},
    {name: 'HDFC Ltd.', nse: 'HDFC', bse: '500010'},
    {name: 'Hero MotoCorp', nse: 'HEROMOTOCO', bse: '500182'},
    {name: 'Hindustan Unilever', nse: 'HINDUNILVR', bse: '500696'},
    {name: 'Hindustan Aeronautics', nse: 'HAL', bse: '541154'},
    {name: 'Hindustan Petroleum', nse: 'HINDPETRO', bse: '500104'},
    {name: 'Hindalco Industries', nse: 'HINDALCO', bse: '500440'},
    {name: 'HCL Technologies', nse: 'HCLTECH', bse: '532281'},
    {name: 'Hindustan Zinc', nse: 'HINDZINC', bse: '500188'},
    {name: 'Hexaware Technologies', nse: 'HEXWARE', bse: '532129'},
    {name: 'Hindustan Motors', nse: 'HINDMOTORS', bse: '500500'},
    {name: 'Havells India', nse: 'HAVELLS', bse: '517354'},
    {name: 'Hindustan Aeronautics Ltd.', nse: 'HAL', bse: '541154'},
    {name: 'Hindustan Construction Company', nse: 'HCC', bse: '500106'},
    {name: 'HDFC Asset Management Company', nse: 'HDFCAMC', bse: '541729'},
    {name: 'Hindustan Coca-Cola Beverages', nse: 'HINDCOKE', bse: '543234'},
    {name: 'HSBC India', nse: 'HSBC', bse: '500105'},
    {name: 'Hindustan Zinc Ltd.', nse: 'HINDZINC', bse: '500188'},
    {name: 'Hindustan Oil Exploration Company', nse: 'HOEC', bse: '500184'},
    {name: 'Hindustan Aeronautics Ltd.', nse: 'HAL', bse: '541154'},
    {name: 'Hindustan Petroleum Corporation', nse: 'HINDPETRO', bse: '500104'},
    {name: 'Hero FinCorp', nse: 'HEROFINCORP', bse: '539107'},
    {name: 'Himadri Speciality Chemical', nse: 'HIMADRI', bse: '526943'},
    {name: 'Hindustan Motors Ltd.', nse: 'HINDMOTORS', bse: '500500'},
    {name: 'Hindustan Aeronautics Limited', nse: 'HAL', bse: '541154'},
    {name: 'Hero MotoCorp Ltd.', nse: 'HEROMOTOCO', bse: '500182'},
    {name: 'HCL Infosystems', nse: 'HCL-INSYS', bse: '500179'},
    {name: 'Hindustan Construction Co. Ltd.', nse: 'HCC', bse: '500106'},
    {name: 'Hindustan Gold Company', nse: 'HINDGOLD', bse: '530671'},
    {name: 'Hero Realty', nse: 'HEROREALTY', bse: '540136'},
    {name: 'Hindustan Motors Ltd.', nse: 'HINDMOTORS', bse: '500500'},
    {name: 'Himadri Speciality Chemical Ltd.', nse: 'HIMADRI', bse: '526943'},
    {name: 'Hindustan Unilever Ltd.', nse: 'HINDUNILVR', bse: '500696'},
    {name: 'HDFC Bank Ltd.', nse: 'HDFCBANK', bse: '500180'},
    {name: 'Hindalco Industries Ltd.', nse: 'HINDALCO', bse: '500440'},
    {name: 'Hindustan Petroleum Corporation Ltd.', nse: 'HINDPETRO', bse: '500104'},
    {name: 'Hero FinCorp Ltd.', nse: 'HEROFINCORP', bse: '539107'},
    {name: 'ICICI Bank', nse: 'ICICIBANK', bse: '532174'},
    {name: 'Infosys', nse: 'INFY', bse: '500209'},
    {name: 'Indian Oil Corporation', nse: 'IOC', bse: '530965'},
    {name: 'IndusInd Bank', nse: 'INDUSINDBK', bse: '535755'},
    {name: 'Indian Railway Catering and Tourism Corporation', nse: 'IRCTC', bse: '542830'},
    {name: 'Indraprastha Medical Corporation', nse: 'IMCL', bse: '532727'},
    {name: 'ICICI Prudential Life Insurance', nse: 'ICICIPRULI', bse: '540133'},
    {name: 'Indian Hotels Company', nse: 'INDHOTEL', bse: '500850'},
    {name: 'IDBI Bank', nse: 'IDBI', bse: '500116'},
    {name: 'IDFC First Bank', nse: 'IDFCFIRSTB', bse: '543321'},
    {name: 'Indian Bank', nse: 'INDIANB', bse: '532814'},
    {name: 'Interglobe Aviation', nse: 'INDIGO', bse: '539448'},
    {name: 'ICICI Lombard General Insurance', nse: 'ICICIGI', bse: '540754'},
    {name: 'India Cements', nse: 'INDIACEM', bse: '530005'},
    {name: 'Indo Count Industries', nse: 'INDOCOUNT', bse: '540548'},
    {name: 'Indian Railway Finance Corporation', nse: 'IRFC', bse: '543259'},
    {name: 'IFCI Ltd.', nse: 'IFCI', bse: '501505'},
    {name: 'Indian Oil Corporation Ltd.', nse: 'IOC', bse: '530965'},
    {name: 'IndusInd Bank Ltd.', nse: 'INDUSINDBK', bse: '535755'},
    {name: 'ICICI Bank Ltd.', nse: 'ICICIBANK', bse: '532174'},
    {name: 'ICICI Prudential Life Insurance Co. Ltd.', nse: 'ICICIPRULI', bse: '540133'},
    {name: 'Indian Railway Catering and Tourism Corp.', nse: 'IRCTC', bse: '542830'},
    {name: 'ICICI Lombard General Insurance Co. Ltd.', nse: 'ICICIGI', bse: '540754'},
    {name: 'Indo Count Industries Ltd.', nse: 'INDOCOUNT', bse: '540548'},
    {name: 'Indian Hotels Company Ltd.', nse: 'INDHOTEL', bse: '500850'},
    {name: 'IDFC First Bank Ltd.', nse: 'IDFCFIRSTB', bse: '543321'},
    {name: 'Indian Bank Ltd.', nse: 'INDIANB', bse: '532814'},
    {name: 'Interglobe Aviation Ltd.', nse: 'INDIGO', bse: '539448'},
    {name: 'India Cements Ltd.', nse: 'INDIACEM', bse: '530005'},
    {name: 'IFCI Ltd.', nse: 'IFCI', bse: '501505'},
    {name: 'IIFL Finance', nse: 'IIFL', bse: '533285'},
    {name: 'Indian Energy Exchange', nse: 'IEX', bse: '540750'},
    {name: 'IndusInd Media and Communications', nse: 'IMCL', bse: '532717'},
    {name: 'ICICI Securities', nse: 'ISEC', bse: '540779'},
    {name: 'Indian Overseas Bank', nse: 'IOB', bse: '532388'},
    {name: 'Indus Towers', nse: 'INDUSTOWER', bse: '540550'},
    {name: 'Indo-Thai Securities', nse: 'ITSL', bse: '539511'},
    {name: 'IIFL Securities', nse: 'IIFLSEC', bse: '540700'},
    {name: 'India Glycols', nse: 'INDGly', bse: '500201'},
    {name: 'Indian Overseas Bank Ltd.', nse: 'IOB', bse: '532388'},
    {name: 'IndusInd Media & Communications Ltd.', nse: 'IMCL', bse: '532717'},
    {name: 'Indian Energy Exchange Ltd.', nse: 'IEX', bse: '540750'},
    {name: 'IIFL Finance Ltd.', nse: 'IIFL', bse: '533285'},
    {name: 'ICICI Securities Ltd.', nse: 'ISEC', bse: '540779'},
    {name: 'Indian Oil Corporation Ltd.', nse: 'IOC', bse: '530965'},
    {name: 'InterGlobe Aviation Ltd.', nse: 'INDIGO', bse: '539448'},
    {name: 'India Cements Ltd.', nse: 'INDIACEM', bse: '530005'},
    {name: 'Jindal Steel & Power', nse: 'JINDALSTEL', bse: '532286'},
    {name: 'JSW Steel', nse: 'JSWSTEEL', bse: '500228'},
    {name: 'Jet Airways', nse: 'JETAIRWAYS', bse: '507989'},
    {name: 'Jubilant FoodWorks', nse: 'JUBLFOOD', bse: '533155'},
    {name: 'Jubilant Life Sciences', nse: 'JUBILANT', bse: '530355'},
    {name: 'Jain Irrigation Systems', nse: 'JISLJALEQS', bse: '500219'},
    {name: 'Jagran Prakashan', nse: 'JAGRAN', bse: '532705'},
    {name: 'Jindal Stainless', nse: 'JINDALSTAIN', bse: '532508'},
    {name: 'Jaiprakash Power Ventures', nse: 'JPPOWER', bse: '533207'},
    {name: 'Jai Corp', nse: 'JAICORPLTD', bse: '532202'},
    {name: 'Jupiter Life Sciences', nse: 'JUPITERS', bse: '541214'},
    {name: 'Jagran Prakashan Ltd.', nse: 'JAGRAN', bse: '532705'},
    {name: 'Jaiswal Chemical Industries', nse: 'JAISWAL', bse: '500205'},
    {name: 'JBM Auto', nse: 'JBMA', bse: '532605'},
    {name: 'JCT Electronics', nse: 'JCT', bse: '500298'},
    {name: 'Jain Irrigation', nse: 'JISLJALEQS', bse: '500219'},
    {name: 'Jaypee Infratech', nse: 'JPINFRATEC', bse: '533207'},
    {name: 'Jai Balaji Industries', nse: 'JAIIB', bse: '532634'},
    {name: 'Jai Corp Ltd.', nse: 'JAICORPLTD', bse: '532202'},
    {name: 'Jaiswal Enterprises', nse: 'JAI', bse: '532589'},
    {name: 'Jaypee Cement', nse: 'JAYPEE', bse: '533207'},
    {name: 'Jagran Prakashan Ltd.', nse: 'JAGRAN', bse: '532705'},
    {name: 'Jindal Poly Films', nse: 'JINDALPOLY', bse: '500227'},
    {name: 'Jubilant FoodWorks Ltd.', nse: 'JUBLFOOD', bse: '533155'},
    {name: 'Jain Irrigation Systems Ltd.', nse: 'JISLJALEQS', bse: '500219'},
    {name: 'JSW Energy', nse: 'JSWENERGY', bse: '533148'},
    {name: 'Jubilant Industries', nse: 'JUBILANTIND', bse: '532690'},
    {name: 'Jagran Prakashan Ltd.', nse: 'JAGRAN', bse: '532705'},
    {name: 'Jaypee Infratech Ltd.', nse: 'JPINFRATEC', bse: '533207'},
    {name: 'Jindal Stainless Steel', nse: 'JINDALSTAIN', bse: '532508'},
    {name: 'Jain Irrigation Systems Ltd.', nse: 'JISLJALEQS', bse: '500219'},
    {name: 'Jai Balaji Industries Ltd.', nse: 'JAIIB', bse: '532634'},
    {name: 'Jubilant Life Sciences Ltd.', nse: 'JUBILANT', bse: '530355'},
    {name: 'Jet Airways (India) Ltd.', nse: 'JETAIRWAYS', bse: '507989'},
    {name: 'JBM Auto Ltd.', nse: 'JBMA', bse: '532605'},
    {name: 'Jindal Steel & Power Ltd.', nse: 'JINDALSTEL', bse: '532286'},
    {name: 'JSW Steel Ltd.', nse: 'JSWSTEEL', bse: '500228'},
    {name: 'Jaiprakash Power Ventures Ltd.', nse: 'JPPOWER', bse: '533207'},
    {name: 'Jagran Prakashan Ltd.', nse: 'JAGRAN', bse: '532705'},
    {name: 'Jai Balaji Industries Ltd.', nse: 'JAIIB', bse: '532634'},
    {name: 'Jubilant Ingrevia Ltd', nse: 'JUBLINGREA', bse: '543271'},
    {name: 'Kotak Mahindra Bank', nse: 'KOTAKBANK', bse: '500247'},
    {name: 'Kansai Nerolac Paints', nse: 'KANSAINER', bse: '500165'},
    {name: 'Kewal Kiran Clothing', nse: 'KEWALKR', bse: '590126'},
    {name: 'Kalpataru Power Transmission', nse: 'KPTL', bse: '522287'},
    {name: 'Kaveri Seed Company', nse: 'KSCL', bse: '519600'},
    {name: 'Karur Vysya Bank', nse: 'KARURVYSYA', bse: '590003'},
    {name: 'KPC Pharmaceuticals', nse: 'KPCPHARMA', bse: '532926'},
    {name: 'Kirloskar Brothers', nse: 'KIRLOSENG', bse: '500241'},
    {name: 'KNR Constructions', nse: 'KNRCON', bse: '539956'},
    {name: 'Kothari Products', nse: 'KOTHARIPRO', bse: '526818'},
    {name: 'Kaveri Seed Co. Ltd.', nse: 'KSCL', bse: '519600'},
    {name: 'Kalpataru Power Transmissions Ltd.', nse: 'KPTL', bse: '522287'},
    {name: 'Kansai Nerolac Paints Ltd.', nse: 'KANSAINER', bse: '500165'},
    {name: 'Kirloskar Electric Co.', nse: 'KIRLOSKE', bse: '500176'},
    {name: 'K P R Mill', nse: 'KPRMILL', bse: '532532'},
    {name: 'Kumar Properties', nse: 'KUMARPROP', bse: '500256'},
    {name: 'Kothari Products Ltd.', nse: 'KOTHARIPRO', bse: '526818'},
    {name: 'Karnataka Bank', nse: 'KTKBANK', bse: '532652'},
    {name: 'KTL International', nse: 'KTIL', bse: '500363'},
    {name: 'KSB Ltd.', nse: 'KSB', bse: '500249'},
    {name: 'Karnataka Power Corporation', nse: 'KPCL', bse: '532695'},
    {name: 'KPR Mill Ltd.', nse: 'KPRMILL', bse: '532248'},
    {name: 'Kothari Sugars & Chemicals', nse: 'KOTHSUGAR', bse: '500295'},
    {name: 'Kewal Kiran Clothing Ltd.', nse: 'KEWALKR', bse: '590126'},
    {name: 'Karnataka Bank Ltd.', nse: 'KTKBANK', bse: '532652'},
    {name: 'Kirloskar Industries', nse: 'KIRLOSIND', bse: '500241'},
    {name: 'Karnataka Power Corporation Ltd.', nse: 'KPCL', bse: '532695'},
    {name: 'KPTL Ltd.', nse: 'KPTL', bse: '522287'},
    {name: 'Kalpataru Power Transmission Ltd.', nse: 'KPTL', bse: '522287'},
    {name: 'Kansai Nerolac Paints Ltd.', nse: 'KANSAINER', bse: '500165'},
    {name: 'Kewal Kiran Clothing Ltd.', nse: 'KEWALKR', bse: '590126'},
    {name: 'Kirloskar Brothers Ltd.', nse: 'KIRLOSENG', bse: '500241'},
    {name: 'Karnataka Power Corporation Ltd.', nse: 'KPCL', bse: '532695'},
    {name: 'Karnataka Bank Ltd.', nse: 'KTKBANK', bse: '532652'},
    {name: 'Kumar Properties Ltd.', nse: 'KUMARPROP', bse: '500256'},
    {name: 'Karnataka Bank', nse: 'KTKBANK', bse: '532652'},
    {name: 'KSL and Industries', nse: 'KSL', bse: '500226'},
    {name: 'Kohinoor Foods', nse: 'KOHL', bse: '507458'},
    {name: 'KNR Constructions Ltd.', nse: 'KNRCON', bse: '539956'},
    {name: 'Kumar Infrastructures', nse: 'KUMARINFR', bse: '540401'},
    {name: 'Karnataka Beverages', nse: 'KARNBEV', bse: '539108'},
    {name: 'Kiran Energy', nse: 'KIRANEN', bse: '543598'},
    {name: 'KPR Mill', nse: 'KPRMILL', bse: '532248'},
    {name: 'Larsen & Toubro', nse: 'LT', bse: '500510'},
    {name: 'Lupin', nse: 'LUPIN', bse: '500257'},
    {name: 'LIC Housing Finance', nse: 'LICHSGFIN', bse: '500253'},
    {name: 'L&T Technology Services', nse: 'LTTS', bse: '540115'},
    {name: 'L&T Finance Holdings', nse: 'LTFH', bse: '533519'},
    {name: 'Laurus Labs', nse: 'LAURUSLABS', bse: '540666'},
    {name: 'Lovable Lingerie', nse: 'LOVABLE', bse: '526405'},
    {name: 'Lakshmi Machine Works', nse: 'LMW', bse: '500252'},
    {name: 'L&T Infotech Mindtree', nse: 'LTIM', bse: '540005'},
    {name: 'Lemon Tree Hotels', nse: 'LEMONTREE', bse: '541233'},
    {name: 'Laurus Labs Ltd.', nse: 'LAURUSLABS', bse: '540666'},
    {name: 'Larsen & Toubro Ltd.', nse: 'LT', bse: '500510'},
    {name: 'Lupin Ltd.', nse: 'LUPIN', bse: '500257'},
    {name: 'LIC Housing Finance Ltd.', nse: 'LICHSGFIN', bse: '500253'},
    {name: 'L&T Technology Services Ltd.', nse: 'LTTS', bse: '540115'},
    {name: 'L&T Finance Holdings Ltd.', nse: 'LTFH', bse: '533519'},
    {name: 'Lakshmi Machine Works Ltd.', nse: 'LMW', bse: '500252'},
    {name: 'Lemon Tree Hotels Ltd.', nse: 'LEMONTREE', bse: '541233'},
    {name: 'Lovable Lingerie Ltd.', nse: 'LOVABLE', bse: '526405'},
    {name: 'L&T Financial Services', nse: 'LTFH', bse: '533519'},
    {name: 'Lloyds Metals and Energy', nse: 'Lloyds', bse: '542651'},
    {name: 'Larsen & Toubro Ltd.', nse: 'LT', bse: '500510'},
    {name: 'Lupin Ltd.', nse: 'LUPIN', bse: '500257'},
    {name: 'LIC Housing Finance Ltd.', nse: 'LICHSGFIN', bse: '500253'},
    {name: 'L&T Technology Services Ltd.', nse: 'LTTS', bse: '540115'},
    {name: 'L&T Finance Holdings Ltd.', nse: 'LTFH', bse: '533519'},
    {name: 'Laurus Labs Ltd.', nse: 'LAURUSLABS', bse: '540666'},
    {name: 'Lovable Lingerie Ltd.', nse: 'LOVABLE', bse: '526405'},
    {name: 'Lakshmi Machine Works Ltd.', nse: 'LMW', bse: '500252'},
    {name: 'Lemon Tree Hotels Ltd.', nse: 'LEMONTREE', bse: '541233'},
    {name: 'Lloyds Metals and Energy Ltd.', nse: 'Lloyds', bse: '542651'},
    {name: 'Larsen & Toubro Infotech Ltd.', nse: 'LTTS', bse: '540115'},
    {name: 'L&T Financial Services Ltd.', nse: 'LTFH', bse: '533519'},
    {name: 'Larsen & Toubro Ltd.', nse: 'LT', bse: '500510'},
    {name: 'Lupin Ltd.', nse: 'LUPIN', bse: '500257'},
    {name: 'LIC Housing Finance Ltd.', nse: 'LICHSGFIN', bse: '500253'},
    {name: 'L&T Technology Services Ltd.', nse: 'LTTS', bse: '540115'},
    {name: 'L&T Finance Holdings Ltd.', nse: 'LTFH', bse: '533519'},
    {name: 'Lakshmi Machine Works Ltd.', nse: 'LMW', bse: '500252'},
    {name: 'Lemon Tree Hotels Ltd.', nse: 'LEMONTREE', bse: '541233'},
    {name: 'Laurus Labs Ltd.', nse: 'LAURUSLABS', bse: '540666'},
    {name: 'Lovable Lingerie Ltd.', nse: 'LOVABLE', bse: '526405'},
    {name: 'Mahindra & Mahindra', nse: 'M&M', bse: '500520'},
    {name: 'Maruti Suzuki', nse: 'MARUTI', bse: '532500'},
    {name: 'Mahindra Finance', nse: 'M&MFIN', bse: '532720'},
    {name: 'Minda Industries', nse: 'MINDAIND', bse: '538962'},
    {name: 'Max Financial Services', nse: 'MAXFIN', bse: '539979'},
    {name: 'Mindtree', nse: 'MINDTREE', bse: '542587'},
    {name: 'Metropolis Healthcare', nse: 'METROPOLIS', bse: '543391'},
    {name: 'MRF', nse: 'MRF', bse: '500290'},
    {name: 'Muthoot Finance', nse: 'MUTHOOTFIN', bse: '533398'},
    {name: 'Minda Corporation', nse: 'MINDACORP', bse: '532539'},
    {name: 'Mangalore Refinery and Petrochemicals', nse: 'MRPL', bse: '532932'},
    {name: 'Mahindra Logistics', nse: 'MLOGISTIC', bse: '540768'},
    {name: 'Manappuram Finance', nse: 'MANAPPURAM', bse: '531213'},
    {name: 'Madhav Marbles', nse: 'MADHAVM', bse: '526127'},
    {name: 'Minda Industries Ltd.', nse: 'MINDAIND', bse: '538962'},
    {name: 'Mahindra & Mahindra Ltd.', nse: 'M&M', bse: '500520'},
    {name: 'Maruti Suzuki India Ltd.', nse: 'MARUTI', bse: '532500'},
    {name: 'Mahindra Finance Ltd.', nse: 'M&MFIN', bse: '532720'},
    {name: 'Max Financial Services Ltd.', nse: 'MAXFIN', bse: '539979'},
    {name: 'Mindtree Ltd.', nse: 'MINDTREE', bse: '542587'},
    {name: 'Metropolis Healthcare Ltd.', nse: 'METROPOLIS', bse: '543391'},
    {name: 'MRF Ltd.', nse: 'MRF', bse: '500290'},
    {name: 'Muthoot Finance Ltd.', nse: 'MUTHOOTFIN', bse: '533398'},
    {name: 'Mangalore Refinery and Petrochemicals Ltd.', nse: 'MRPL', bse: '532932'},
    {name: 'Mahindra Logistics Ltd.', nse: 'MLOGISTIC', bse: '540768'},
    {name: 'Manappuram Finance Ltd.', nse: 'MANAPPURAM', bse: '531213'},
    {name: 'Madhav Marbles Ltd.', nse: 'MADHAVM', bse: '526127'},
    {name: 'Minda Corporation Ltd.', nse: 'MINDACORP', bse: '532539'},
    {name: 'Mahindra Intertrade', nse: 'MINDTRA', bse: '532112'},
    {name: 'Mahindra Susten', nse: 'MINDRA', bse: '539874'},
    {name: 'Madhya Bharat Agro Products', nse: 'MBAPL', bse: '519303'},
    {name: 'Mahindra Reva Electric Vehicles', nse: 'MAHINDRARE', bse: '542163'},
    {name: 'Mangalam Cement', nse: 'MANGALAM', bse: '500124'},
    {name: 'Mas Financial Services', nse: 'MASFIN', bse: '541922'},
    {name: 'Minda Industries Ltd.', nse: 'MINDAIND', bse: '538962'},
    {name: 'Mangalore Refinery & Petrochemicals Ltd.', nse: 'MRPL', bse: '532932'},
    {name: 'Mahindra Susten Ltd.', nse: 'MINDRA', bse: '539874'},
    {name: 'Madhya Bharat Agro Products Ltd.', nse: 'MBAPL', bse: '519303'},
    {name: 'Madhav Marbles & Granites Ltd.', nse: 'MADHAVM', bse: '526127'},
    {name: 'Max Financial Services Ltd.', nse: 'MAXFIN', bse: '539979'},
    {name: 'Mahindra Finance Ltd.', nse: 'M&MFIN', bse: '532720'},
    {name: 'Mahindra & Mahindra Ltd.', nse: 'M&M', bse: '500520'},
    {name: 'Muthoot Finance Ltd.', nse: 'MUTHOOTFIN', bse: '533398'},
    {name: 'Nestle India', nse: 'NESTLEIND', bse: '500790'},
    {name: 'NTPC', nse: 'NTPC', bse: '532555'},
    {name: 'Nagarjuna Fertilizers', nse: 'NAGAFERT', bse: '500404'},
    {name: 'Nifty Beverages', nse: 'NIFTYBEV', bse: '539327'},
    {name: 'Nerolac Paints', nse: 'NEROLAC', bse: '500165'},
    {name: 'Nirma', nse: 'NIRMA', bse: '500302'},
    {name: 'NIIT', nse: 'NIIT', bse: '500304'},
    {name: 'NCC Ltd.', nse: 'NCC', bse: '532401'},
    {name: 'Nagarjuna Oil Refinery', nse: 'NAGAROIL', bse: '532594'},
    {name: 'National Fertilizers', nse: 'NFL', bse: '500066'},
    {name: 'NSE', nse: 'NSE', bse: 'N/A'},
    {name: 'Nestle India Ltd.', nse: 'NESTLEIND', bse: '500790'},
    {name: 'NTPC Ltd.', nse: 'NTPC', bse: '532555'},
    {name: 'Nagarjuna Fertilizers Ltd.', nse: 'NAGAFERT', bse: '500404'},
    {name: 'Nifty Beverages Ltd.', nse: 'NIFTYBEV', bse: '539327'},
    {name: 'Nerolac Paints Ltd.', nse: 'NEROLAC', bse: '500165'},
    {name: 'Nirma Ltd.', nse: 'NIRMA', bse: '500302'},
    {name: 'NIIT Ltd.', nse: 'NIIT', bse: '500304'},
    {name: 'NCC Ltd.', nse: 'NCC', bse: '532401'},
    {name: 'Nagarjuna Oil Refinery Ltd.', nse: 'NAGAROIL', bse: '532594'},
    {name: 'National Fertilizers Ltd.', nse: 'NFL', bse: '500066'},
    {name: 'NSE Ltd.', nse: 'NSE', bse: 'N/A'},
    {name: 'Navin Fluorine International', nse: 'NAVINFLUOR', bse: '513268'},
    {name: 'Nashik Industries', nse: 'NASHIKIND', bse: '539288'},
    {name: 'Nagarjuna Agrichem', nse: 'NAGARJUNA', bse: '524726'},
    {name: 'New India Assurance', nse: 'NEWINDIA', bse: '540133'},
    {name: 'Nahar Industrial Enterprises', nse: 'NAHARIND', bse: '514166'},
    {name: 'National Aluminium Company', nse: 'NALCO', bse: '532234'},
    {name: 'Nandan Denim', nse: 'NANDANDENIM', bse: '540076'},
    {name: 'Nucleus Software Exports', nse: 'Nucleus', bse: '532403'},
    {name: 'Neuland Laboratories', nse: 'NEULANDLAB', bse: '524558'},
    {name: 'Nitin Spinners', nse: 'NITINSPIN', bse: '514110'},
    {name: 'Nivara', nse: 'NIVARA', bse: 'N/A'},
    {name: 'Nashik Industries Ltd.', nse: 'NASHIKIND', bse: '539288'},
    {name: 'Navin Fluorine Ltd.', nse: 'NAVINFLUOR', bse: '513268'},
    {name: 'Nagarjuna Fertilizers Ltd.', nse: 'NAGAFERT', bse: '500404'},
    {name: 'Nifty Beverages Ltd.', nse: 'NIFTYBEV', bse: '539327'},
    {name: 'National Fertilizers Ltd.', nse: 'NFL', bse: '500066'},
    {name: 'Nifty Global', nse: 'NIFTYGLB', bse: 'N/A'},
    {name: 'Nirma Ltd.', nse: 'NIRMA', bse: '500302'},
    {name: 'Nagarjuna Oil Refinery Ltd.', nse: 'NAGAROIL', bse: '532594'},
    {name: 'NCC Ltd.', nse: 'NCC', bse: '532401'},
    {name: 'NSE Ltd.', nse: 'NSE', bse: 'N/A'},
    {name: 'Oil and Natural Gas Corporation', nse: 'ONGC', bse: '500312'},
    {name: 'Oracle Financial Services', nse: 'OFSS', bse: '532448'},
    {name: 'Oberoi Realty', nse: 'OBEROIRLTY', bse: '533273'},
    {name: 'Omaxe', nse: 'OMAXE', bse: '532880'},
    {name: 'Orient Cement', nse: 'ORIENTCEM', bse: '534829'},
    {name: 'Oberoi Hotels & Resorts', nse: 'OHRL', bse: 'N/A'},
    {name: 'Oil India', nse: 'OILINDIA', bse: '533106'},
    {name: 'Odisha Mining Corporation', nse: 'OMC', bse: 'N/A'},
    {name: 'OnMobile Global', nse: 'ONMOBILE', bse: '532944'},
    {name: 'Olympia Industries', nse: 'OLYMPIA', bse: 'N/A'},
    {name: 'One97 Communications', nse: 'PAYTM', bse: '543396'},
    {name: 'Omkar Speciality Chemicals', nse: 'OMKAR', bse: '530019'},
    {name: 'Overseas Infrastructure Alliance', nse: 'OIA', bse: 'N/A'},
    {name: 'Orbit Corporation', nse: 'ORBITCORP', bse: '532860'},
    {name: 'Onward Technologies', nse: 'ONWARDTEC', bse: '532440'},
    {name: 'Opto Circuits', nse: 'OPT', bse: '532391'},
    {name: 'Olympia Industries Ltd.', nse: 'OLYMPIA', bse: 'N/A'},
    {name: 'Oberoi Realty Ltd.', nse: 'OBEROIRLTY', bse: '533273'},
    {name: 'Orient Cement Ltd.', nse: 'ORIENTCEM', bse: '534829'},
    {name: 'Omaxe Ltd.', nse: 'OMAXE', bse: '532880'},
    {name: 'Oil and Natural Gas Corporation Ltd.', nse: 'ONGC', bse: '500312'},
    {name: 'Oil India Ltd.', nse: 'OILINDIA', bse: '533106'},
    {name: 'OnMobile Global Ltd.', nse: 'ONMOBILE', bse: '532944'},
    {name: 'Opto Circuits (India) Ltd.', nse: 'OPT', bse: '532391'},
    {name: 'Omkar Speciality Chemicals Ltd.', nse: 'OMKAR', bse: '530019'},
    {name: 'Overseas Infrastructure Alliance Ltd.', nse: 'OIA', bse: 'N/A'},
    {name: 'Orbit Corporation Ltd.', nse: 'ORBITCORP', bse: '532860'},
    {name: 'Onward Technologies Ltd.', nse: 'ONWARDTEC', bse: '532440'},
    {name: 'Oracle Financial Services Software Ltd.', nse: 'OFSS', bse: '532448'},
    {name: 'Hindustan Petroleum', nse: 'HPCL', bse: '500104'},
    {name: 'Power Grid Corporation', nse: 'POWERGRID', bse: '532898'},
    {name: 'Pidilite Industries', nse: 'PIDILITIND', bse: '500331'},
    {name: 'PVR', nse: 'PVR', bse: '532689'},
    {name: 'Punjab National Bank', nse: 'PNB', bse: '532461'},
    {name: 'Page Industries', nse: 'PAGEIND', bse: '532827'},
    {name: 'Petronet LNG', nse: 'PETRONET', bse: '532522'},
    {name: 'Phoenix Mills', nse: 'PHOENIXLTD', bse: '503100'},
    {name: 'Power Finance Corporation', nse: 'PFC', bse: '532810'},
    {name: 'Polycab India', nse: 'POLYCAB', bse: '542652'},
    {name: 'Praja', nse: 'PRAJIND', bse: '523598'},
    {name: 'Poonawalla Fincorp', nse: 'POONAWALLA', bse: '543261'},
    {name: 'Prakash Industries', nse: 'PRAKASH', bse: '530199'},
    {name: 'Prestige Estates', nse: 'PRESTIGE', bse: '533274'},
    {name: 'PFC', nse: 'PFC', bse: '532810'},
    {name: 'Punjab National Bank Ltd.', nse: 'PNB', bse: '532461'},
    {name: 'Page Industries Ltd.', nse: 'PAGEIND', bse: '532827'},
    {name: 'Petronet LNG Ltd.', nse: 'PETRONET', bse: '532522'},
    {name: 'Power Grid Corporation of India Ltd.', nse: 'POWERGRID', bse: '532898'},
    {name: 'Pidilite Industries Ltd.', nse: 'PIDILITIND', bse: '500331'},
    {name: 'PVR Ltd.', nse: 'PVR', bse: '532689'},
    {name: 'Phoenix Mills Ltd.', nse: 'PHOENIXLTD', bse: '503100'},
    {name: 'Polycab India Ltd.', nse: 'POLYCAB', bse: '542652'},
    {name: 'Power Finance Corporation Ltd.', nse: 'PFC', bse: '532810'},
    {name: 'Praja Industries Ltd.', nse: 'PRAJIND', bse: '523598'},
    {name: 'Poonawalla Fincorp Ltd.', nse: 'POONAWALLA', bse: '543261'},
    {name: 'Prakash Industries Ltd.', nse: 'PRAKASH', bse: '530199'},
    {name: 'Prestige Estates Projects Ltd.', nse: 'PRESTIGE', bse: '533274'},
    {name: 'PVR Cinemas', nse: 'PVR', bse: '532689'},
    {name: 'Philips Carbon Black', nse: 'PHILIPCARB', bse: '506590'},
    {name: 'Procter & Gamble Health', nse: 'PGHH', bse: '500459'},
    {name: 'Punjab Alkalies & Chemicals', nse: 'PACL', bse: '500372'},
    {name: 'Pollution Control', nse: 'POLLUTION', bse: '532973'},
    {name: 'Quess Corp', nse: 'QUESS', bse: '539978'},
    {name: 'Quest Global Services', nse: 'QUEST', bse: 'N/A'},
    {name: 'Reliance Industries', nse: 'RELIANCE', bse: '500325'},
    {name: 'Raymond', nse: 'RAYMOND', bse: '500330'},
    {name: 'RIL', nse: 'RIL', bse: '500325'},
    {name: 'Ramco Cements', nse: 'RAMCOCEM', bse: '500260'},
    {name: 'Rural Electrification Corporation', nse: 'REC', bse: '532955'},
    {name: 'Ruchi Soya', nse: 'RUCHISOYA', bse: '540150'},
    {name: 'Redington', nse: 'REDINGTON', bse: '521064'},
    {name: 'Rolta India', nse: 'ROLTA', bse: '500366'},
    {name: 'Rashtriya Chemicals and Fertilizers', nse: 'RCF', bse: '506768'},
    {name: 'Rail Vikas Nigam', nse: 'RVNL', bse: '541556'},
    {name: 'State Bank of India', nse: 'SBIN', bse: '500112'},
    {name: 'SBI Life Insurance', nse: 'SBILIFE', bse: '540719'},
    {name: 'SBI Cards and Payment Services', nse: 'SBICARD', bse: '543066'},
    {name: 'Sun Pharmaceutical Industries', nse: 'SUNPHARMA', bse: '524715'},
    {name: 'Shree Cement', nse: 'SHREECEM', bse: '502355'},
    {name: 'Steel Authority of India', nse: 'SAIL', bse: '500113'},
    {name: 'Shree Renuka Sugars', nse: 'RENUKA', bse: '532490'},
    {name: 'Siemens', nse: 'SIEMENS', bse: '500550'},
    {name: 'Sundaram Finance', nse: 'SUNDARAMFIN', bse: '590071'},
    {name: 'Sasken Technologies', nse: 'SASKEN', bse: '532663'},
    {name: 'Scripbox', nse: 'SCRIPBOX', bse: 'N/A'},
    {name: 'South Indian Bank', nse: 'SOUTHBANK', bse: '532218'},
    {name: 'Sanofi India', nse: 'SANOFIINDIA', bse: '500674'},
    {name: 'Sah Polymers', nse: 'SAHPOLY', bse: 'N/A'},
    {name: 'Sundaram Clayton', nse: 'SUNCLAYLTD', bse: '500258'},
    {name: 'South Eastern Coalfields', nse: 'SECL', bse: 'N/A'},
    {name: 'Sahara One Media & Entertainment', nse: 'SOMEC', bse: 'N/A'},
    {name: 'Sagar Cements', nse: 'SAGCEM', bse: '502405'},
    {name: 'Satyam Computer Services', nse: 'SATYAMCOMP', bse: 'N/A'},
    {name: 'Sanjay Leela Bhansali', nse: 'SLB', bse: 'N/A'},
    {name: 'Syngene International', nse: 'SYGN', bse: '539268'},
    {name: 'State Bank of India', nse: 'SBIN', bse: '500112'},
    {name: 'SBI Life Insurance', nse: 'SBILIFE', bse: '540719'},
    {name: 'Sun Pharmaceutical Industries', nse: 'SUNPHARMA', bse: '524715'},
    {name: 'Shree Cement', nse: 'SHREECEM', bse: '502355'},
    {name: 'Shree Renuka Sugars', nse: 'RENUKA', bse: '532490'},
    {name: 'Siemens', nse: 'SIEMENS', bse: '500550'},
    {name: 'Sasken Technologies', nse: 'SASKEN', bse: '532663'},
    {name: 'South Indian Bank', nse: 'SOUTHBANK', bse: '532218'},
    {name: 'Sanofi India', nse: 'SANOFIINDIA', bse: '500674'},
    {name: 'Sahara One Media & Entertainment', nse: 'SOMEC', bse: 'N/A'},
    {name: 'Sagar Cements', nse: 'SAGCEM', bse: '502405'},
    {name: 'Satyam Computer Services', nse: 'SATYAMCOMP', bse: 'N/A'},
    {name: 'Syngene International', nse: 'SYGN', bse: '539268'},
    {name: 'Sula Vineyards', nse: 'SULAVINEY', bse: 'N/A'},
    {name: 'Shree Renuka Sugar Ltd.', nse: 'RENUKA', bse: '532490'},
    {name: 'Sukhjit Starch & Chemicals', nse: 'SUJHIT', bse: '530203'},
    {name: 'SJVN Ltd.', nse: 'SJVN', bse: '533206'},
    {name: 'Sapphire Foods India', nse: 'Sapphire', bse: 'N/A'},
    {name: 'Samvardhana Motherson International', nse: 'MOTHERSON', bse: 'N/A'},
    {name: 'Tata Consultancy Services', nse: 'TCS', bse: '532540'},
    {name: 'Tata Steel', nse: 'TATASTEEL', bse: '500470'},
    {name: 'Tata Motors', nse: 'TATAMOTORS', bse: '500570'},
    {name: 'Tata Power', nse: 'TATAPOWER', bse: '500400'},
    {name: 'Tech Mahindra', nse: 'TECHM', bse: '532755'},
    {name: 'Torrent Pharmaceuticals', nse: 'TORNTPHARM', bse: '500420'},
    {name: 'Titan Company', nse: 'TITAN', bse: '500114'},
    {name: 'Trent', nse: 'TRENT', bse: '504776'},
    {name: 'Tata Elxsi', nse: 'TATAELXSI', bse: '500408'},
    {name: 'TVS Motor Company', nse: 'TVSMOTOR', bse: '532343'},
    {name: 'Tata Chemicals', nse: 'TATACHEM', bse: '500770'},
    {name: 'Tata Communications', nse: 'TATACOMM', bse: '500483'},
    {name: 'Tube Investments of India', nse: 'TIINDIA', bse: '504973'},
    {name: 'Tata Teleservices', nse: 'TTML', bse: '532371'},
    {name: 'Thomas Cook', nse: 'THOMASCOOK', bse: '500413'},
    {name: 'Triveni Engineering', nse: 'TRIVENI', bse: '531288'},
    {name: 'Tata Advanced Systems', nse: 'TAS', bse: 'N/A'},
    {name: 'Thyrocare Technologies', nse: 'THYROCARE', bse: '540857'},
    {name: 'Tata Coffee', nse: 'TATACOFFEE', bse: '533259'},
    {name: 'Timken India', nse: 'TIMKEN', bse: '505890'},
    {name: 'Trident', nse: 'TRIDENT', bse: '531301'},
    {name: 'UltraTech Cement', nse: 'ULTRACEMCO', bse: '532538'},
    {name: 'UPL', nse: 'UPL', bse: '512070'},
    {name: 'Union Bank of India', nse: 'UNIONBANK', bse: '532477'},
    {name: 'United Breweries', nse: 'UBBREW', bse: '532478'},
    {name: 'United Spirits', nse: 'UNITEDSPIRITS', bse: '532432'},
    {name: 'Unichem Laboratories', nse: 'UNICHEMLAB', bse: '506690'},
    {name: 'Ujjivan Financial Services', nse: 'UJJIVANSFB', bse: 'UJJIVANSFB'},
    {name: 'UFO Moviez India', nse: 'UFOMOVIEZ', bse: '532800'},
    {name: 'Udaipur Cement Works', nse: 'UDAICEM', bse: '533398'},
    {name: 'United Bank of India', nse: 'UNITEDBANK', bse: '532535'},
    {name: 'Wipro', nse: 'WIPRO', bse: '507685'},
    {name: 'Whirlpool of India', nse: 'WHIRLPOOL', bse: '500097'},
    {name: 'Wabco India', nse: 'WABCOINDIA', bse: '505400'},
    {name: 'Waaree Energies Ltd', nse: 'WAAREEENER', bse: '544277'},
    {name: 'Wellness Forever Medicare', nse: 'WELLNESS', bse: 'N/A'},
    {name: 'Westlife Development', nse: 'WESTLIFE', bse: '540135'},
    {name: 'Walchandnagar Industries', nse: 'WALCHANNAGAR', bse: '500384'},
    {name: 'Xelpmoc Design and Tech', nse: 'XELPMOC', bse: 'N/A'},
    {name: 'Xchanging Solutions', nse: 'XCHANGING', bse: 'N/A'},
    {name: 'Yes Bank', nse: 'YESBANK', bse: '532648'},
    {name: 'Yatra Online', nse: 'YATRA', bse: 'N/A'},
    {name: 'Yash Pakka', nse: 'YASHPAKKA', bse: 'N/A'},
    {name: 'Zee Entertainment Enterprises', nse: 'ZEEL', bse: '505537'},
    {name: 'Zydus Cadila', nse: 'ZYDUSLIFE', bse: '532321'}
];

const removeDuplicatesAndKey = (array) => {
    const seenNSE = new Set();
    const nseCleaned = array.reduce((acc, item) => {
        const key = item.nse;
        if (!seenNSE.has(key)) {
            seenNSE.add(key);
            acc.push(item);
        }
        return acc;
    }, []);

    const seenBSE = new Set();
    const nsebseCleaned = nseCleaned.reduce((acc, item) => {
        const key = item.bse;
        if (key === 'N/A' || !seenBSE.has(key)) {
            seenBSE.add(key);
            acc.push(item);
        } else {
            console.log('Rejected: ', item);
        }
        return acc;
    }, []);

    return nsebseCleaned;
};

const filePath = './data/common/scriptList.json';
const uniqueStocks = removeDuplicatesAndKey(stocks);

fs.writeFile(filePath, JSON.stringify(uniqueStocks, null, 2), (err) => {
    if (err) {
        console.log({message: 'Error saving data', error: err});
    }
    console.log({message: 'Data saved successfully!'});
});
